<?php

namespace PTV\Routing\Enums;

enum EtcSubscriptionType: string
{
    case AT_GOBOX = "AT_GOBOX";
    case BE_TELETOL = "BE_TELETOL";
    case BE_VIAPASS = "BE_VIAPASS";
    case CH_LSVA = "CH_LSVA";
    case DE_QUICKBOX = "DE_QUICKBOX";
    case DE_TOLLCOLLECT = "DE_TOLLCOLLECT";
    case DE_WARNOWTUNNEL_RFID = "DE_WARNOWTUNNEL_RFID";
    case DK_BROPAS_BUSINESS = "DK_BROPAS_BUSINESS";
    case IT_TELEPASS = "IT_TELEPASS";
    case NL_TELECARD = "NL_TELECARD";
    case NL_TTAG = "NL_TTAG";
    case NO_AUTOPASS = "NO_AUTOPASS";
    case PT_VIA_VERDE = "PT_VIA_VERDE";
    case US_APASS = "US_APASS";
    case US_BREEZEBY = "US_BREEZEBY";
    case US_DOWNBEACH_EXPRESSPASS = "US_DOWNBEACH_EXPRESSPASS";
    case US_EPASS = "US_EPASS";
    case US_EXPRESSACCOUNT = "US_EXPRESSACCOUNT";
    case US_EXPRESSCARD = "US_EXPRESSCARD";
    case US_EXPRESSPASS = "US_EXPRESSPASS";
    case US_EXPRESSTOLL = "US_EXPRESSTOLL";
    case US_EZPASS = "US_EZPASS";
    case US_EZTAG = "US_EZTAG";
    case US_FASTRAK = "US_FASTRAK";
    case US_GEAUXPASS = "US_GEAUXPASS";
    case US_GOODTOGO = "US_GOODTOGO";
    case US_GOPASS = "US_GOPASS";
    case US_IPASS = "US_IPASS";
    case US_KTAG = "US_KTAG";
    case US_LEEWAY = "US_LEEWAY";
    case US_MACKINACBRIDGE_MACPASS = "US_MACKINACBRIDGE_MACPASS";
    case US_MARYLAND_EZPASS = "US_MARYLAND_EZPASS";
    case US_MASSACHUSETTS_EZPASS = "US_MASSACHUSETTS_EZPASS";
    case US_NC_QUICKPASS = "US_NC_QUICKPASS";
    case US_NEWHAMPSHIRE_EZPASS = "US_NEWHAMPSHIRE_EZPASS";
    case US_NEWJERSEY_EZPASS = "US_NEWJERSEY_EZPASS";
    case US_NEWYORK_EZPASS = "US_NEWYORK_EZPASS";
    case US_NEXPRESS = "US_NEXPRESS";
    case US_OHIO_EZPASS = "US_OHIO_EZPASS";
    case US_PALPASS = "US_PALPASS";
    case US_PIKEPASS = "US_PIKEPASS";
    case US_RIVERLINK = "US_RIVERLINK";
    case US_RIVERLINK_NOTRANSPONDER = "US_RIVERLINK_NOTRANSPONDER";
    case US_SEAWAYTRANSITCARD = "US_SEAWAYTRANSITCARD";
    case US_SUNPASS = "US_SUNPASS";
    case US_TOLLTAG = "US_TOLLTAG";
    case US_TXTAG = "US_TXTAG";
    case US_VIRGINIA_EZPASS = "US_VIRGINIA_EZPASS";
    case US_WESTVIRGINIA_EZPASS = "US_WESTVIRGINIA_EZPASS";
    case US_PEACHPASS = "US_PEACHPASS";
    case US_NEXUS = "US_NEXUS";
    case US_DELAWARE_EZPASS = "US_DELAWARE_EZPASS";
    case US_GROSSEILETOLLBRIDGE_PASSTAG = "US_GROSSEILETOLLBRIDGE_PASSTAG";
    case US_EZPASS_PAYBYPLATE = "US_EZPASS_PAYBYPLATE";
}
